/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gscript.vm;

import std.stdio;
import std.conv;
import std.traits;
import std.algorithm;
import std.array;
import std.ascii;

import gscript.instruction_set;
import gscript.dynamic;
import gscript.labelmap;
import gscript.stdlib.str;
import gscript.stdlib.io;
import gscript.stdlib.time;

interface GsObject
{
    GsDynamic get(string key);
    void set(string key, GsDynamic value);
    bool contains(string key);
    void setPrototype(GsObject);
    
    //GsObject dup();
    
    final GsDynamic opIndex(string key)
    {
        if (contains(key))
            return get(key);
        else
            return GsDynamic();
    }
    
    final T opIndexAssign(T)(T value, string key)
    {
        set(key, GsDynamic(value));
        return value;
    }
}

class GsGCObject: GsObject
{
    protected:
    
    GsObject prototype;
    GsDynamic[string] storage;
    
    public:
    
    this()
    {
    }

    GsDynamic get(string key)
    {
        auto v = key in storage;
        if (v)
            return *v;
        else
        {
            if (prototype)
                return prototype.get(key);
            else
                return GsDynamic();
        }
    }

    void set(string key, GsDynamic value)
    {
        storage[key] = value;
    }

    bool contains(string key)
    {
        if ((key in storage) !is null)
            return true;
        else
        {
            if (prototype)
                return prototype.contains(key);
            else
                return false;
        }
    }
    
    void setPrototype(GsObject proto)
    {
        prototype = proto;
    }
    
    /*
    GsObject dup()
    {
        GsGCObject newObj = new GsGCObject();
        foreach(key, value; storage)
        {
            newObj.set(key, value);
        }
        return newObj;
    }
    */
}

struct GsCallFrame
{
    GsDynamic[128] parameters;
    GsDynamic[128] localVariables;
    size_t numParameters;
}

GsDynamic vmBuiltinRemove(GsDynamic[] args)
{
    if (args.length < 2)
        return args[0];
    
    if (args[0].type != GsDynamicType.Array)
        return args[0];
    
    auto arr = args[0].asArray;
    if (arr.length == 0)
        return GsDynamic(arr);
    
    auto removeIndex = cast(size_t)args[1].asNumber;
    auto newArr = new GsDynamic[arr.length - 1];
    for (size_t i = 0; i < arr.length; i++)
    {
        if (i < removeIndex)
            newArr[i] = arr[i];
        else if (i > removeIndex)
            newArr[i - 1] = arr[i];
    }
    return GsDynamic(newArr);
}

GsDynamic vmBuiltinRemoveFront(GsDynamic[] args)
{
    if (args[0].type != GsDynamicType.Array)
        return args[0];
    
    auto arr = args[0].asArray;
    if (arr.length == 0)
        return GsDynamic(arr);
    
    auto newArr = new GsDynamic[arr.length - 1];
    for (size_t i = 1; i < arr.length; i++)
    {
        newArr[i - 1] = arr[i];
    }
    return GsDynamic(newArr);
}

GsDynamic vmBuiltinRemoveBack(GsDynamic[] args)
{
    if (args[0].type != GsDynamicType.Array)
        return args[0];
    
    auto arr = args[0].asArray;
    if (arr.length == 0)
        return GsDynamic(arr);
    
    auto newArr = new GsDynamic[arr.length - 1];
    for (size_t i = 0; i < newArr.length; i++)
    {
        newArr[i] = arr[i];
    }
    return GsDynamic(newArr);
}

GsDynamic vmBuiltinInsert(GsDynamic[] args)
{
    if (args.length < 3)
        return args[0];
    
    if (args[0].type != GsDynamicType.Array)
        return args[0];
    
    auto arr = args[0].asArray;
    auto insertIndex = cast(size_t)args[1].asNumber;
    if (insertIndex < 0)
        return args[0];
    
    auto value = args[2];
    
    auto newArr = new GsDynamic[arr.length + 1];
    for (size_t i = 0; i < newArr.length; i++)
    {
        if (i < insertIndex)
            newArr[i] = arr[i];
        else if (i == insertIndex)
            newArr[i] = value;
        else
            newArr[i] = arr[i - 1];
    }
    return GsDynamic(newArr);
}

GsDynamic vmBuiltinSlice(GsDynamic[] args)
{
    if (args.length < 3)
        return args[0];
    
    if (args[0].type != GsDynamicType.Array)
        return args[0];
    
    auto arr = args[0].asArray;
    
    auto sliceStartIndex = cast(size_t)args[1].asNumber;
    if (sliceStartIndex < 0 || sliceStartIndex >= arr.length)
        return args[0];
    
    auto sliceEndIndex = cast(size_t)args[2].asNumber;
    if (sliceEndIndex < sliceStartIndex || sliceEndIndex > arr.length)
        return args[0];
    
    if (sliceEndIndex == sliceStartIndex)
        return GsDynamic([]);
    else
        return GsDynamic(arr[sliceStartIndex..sliceEndIndex]);
}

class GsVirtualMachine: GsObject
{
  protected:
    GsDynamic[] stack;
    GsInstruction[] instructions;
    size_t[] callStack;            // Call stack for subroutine return addresses
    GsCallFrame[] callFrames;      // Stack of call frames
    size_t ip;                     // Instruction pointer
    size_t sp;                     // Stack pointer
    size_t cp;                     // Call stack pointer

    LabelMap jumpTable;            // Function table mapping names to instruction indices
    GsDynamic[string] globals;     // Built-in variables
    GsDynamic[string] builtins;    // Built-in methods
    
    GsGlobalStr globStr;
    GsGlobalIO globIO;
    GsGlobalTime globTime;
    
    size_t callDepth = 1;
    
  public:

    this()
    {
        this.stack = new GsDynamic[256];        // Fixed stack size
        this.callStack = new size_t[256];       // Fixed call stack size
        this.callFrames = new GsCallFrame[256]; // Initialize empty call stack
        this.ip = 0;
        this.sp = 0;
        this.cp = 0;
        
        jumpTable = new LabelMap(1000000);
        
        builtins["remove"] = GsDynamic(&vmBuiltinRemove);
        builtins["removeFront"] = GsDynamic(&vmBuiltinRemoveFront);
        builtins["removeBack"] = GsDynamic(&vmBuiltinRemoveBack);
        builtins["insert"] = GsDynamic(&vmBuiltinInsert);
        builtins["slice"] = GsDynamic(&vmBuiltinSlice);
        
        globStr = new GsGlobalStr();
        globals["string"] = GsDynamic(globStr);
        
        globIO = new GsGlobalIO();
        globals["io"] = GsDynamic(globIO);
        
        globTime = new GsGlobalTime();
        globals["time"] = GsDynamic(globTime);
    }
    
    GsDynamic get(string key)
    {
        auto v = key in globals;
        if (v)
            return *v;
        else
            return GsDynamic(cast(double)0.0);
    }

    void set(string key, GsDynamic value)
    {
        globals[key] = value;
    }

    bool contains(string key)
    {
        return (key in globals) !is null;
    }
    
    void setPrototype(GsObject proto)
    {
        // No-op
    }
    
    /*
    GsObject dup()
    {
        GsGCObject newObj = new GsGCObject();
        foreach(key, value; globals)
        {
            newObj.set(key, value);
        }
        return newObj;
    }
    */

    // Stack manipulation methods
    GsDynamic pop()
    {
        if (sp == 0)
        {
            throw new Exception("Stack underflow");
        }
        return stack[--sp];
    }

    GsDynamic peek()
    {
        if (sp == 0)
        {
            throw new Exception("Stack is empty");
        }
        return stack[sp - 1];
    }

    void push(GsDynamic value)
    {
        if (sp >= stack.length)
        {
            throw new Exception("Stack overflow");
        }
        stack[sp++] = value;
    }
    
    GsObject createObject()
    {
        return new GsGCObject();
    }
    
    GsDynamic[] createArray(size_t len)
    {
        return new GsDynamic[len];
    }
    
    bool hasLabel(string name)
    {
        return (name in jumpTable) != null;
    }
    
    void call(string jumpLabel, GsDynamic[] args)
    {
        if (jumpLabel in jumpTable)
        {
            auto callFrame = &callFrames[0];
            for(size_t i = 0; i < args.length; i++)
            {
                callFrame.parameters[i] = args[i];
            }
            callFrame.numParameters = args.length;
            callDepth = 0;
            run(jumpTable[jumpLabel], 0);
        }
        else
        {
            writeln("Error: unknown jump label \"", jumpLabel, "\"");
        }
    }

    void load(GsInstruction[] instructions)
    {
        if (instructions[$-1].type != GsInstructionType.HALT)
            this.instructions = instructions ~ GsInstruction(GsInstructionType.HALT);
        else
            this.instructions = instructions;
        
        // Populate the function table with label indices
        foreach(i, instrunction; instructions)
        {
            if (instrunction.type == GsInstructionType.LABEL)
            {
                jumpTable[instrunction.operand.asString] = i;
            }
        }
        
        finalize();
    }
    
    void finalize()
    {
        ip = instructions.length - 1;
    }
    
    void run(size_t initialIp = 0, size_t initialCallDepth = 1)
    {
        ip = initialIp;
        sp = 0;
        cp = 0;
        GsCallFrame* callFrame = &callFrames[cp];
        callDepth = initialCallDepth;
        
        while (ip < instructions.length)
        {
            auto instruction = instructions[ip++];
            switch (instruction.type)
            {
                case GsInstructionType.LABEL:
                    break;
                case GsInstructionType.PUSH:
                    push(instruction.operand);
                    break;
                case GsInstructionType.POP:
                    pop();
                    break;
                case GsInstructionType.ADD:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber + b.asNumber));
                    else
                    {
                        writefln("Fatality: addition of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.SUB:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber - b.asNumber));
                    else
                    {
                        writefln("Fatality: subtraction of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.MUL:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber * b.asNumber));
                    else
                    {
                        writefln("Fatality: multiplication of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.DIV:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber / b.asNumber));
                    else
                    {
                        writefln("Fatality: division of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.NEG:
                    auto a = pop();
                    if (a.type == GsDynamicType.Number)
                        push(GsDynamic(-a.asNumber));
                    else
                    {
                        writefln("Fatality: negation of %s", a.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.MOD:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber % b.asNumber));
                    else
                    {
                        writefln("Fatality: modulo of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.POW:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber ^^ b.asNumber));
                    else
                    {
                        writefln("Fatality: power of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.BITWISE_AND:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(cast(long)a.asNumber & cast(long)b.asNumber));
                    else
                    {
                        writefln("Fatality: bitwise AND of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.BITWISE_OR:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(cast(long)a.asNumber | cast(long)b.asNumber));
                    else
                    {
                        writefln("Fatality: bitwise OR of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.BITWISE_XOR:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(cast(long)a.asNumber ^ cast(long)b.asNumber));
                    else
                    {
                        writefln("Fatality: bitwise XOR of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.AND:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber && b.asNumber));
                    else
                    {
                        writefln("Fatality: logical AND of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.OR:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Number && b.type == GsDynamicType.Number)
                        push(GsDynamic(a.asNumber || b.asNumber));
                    else
                    {
                        writefln("Fatality: logical OR of %s and %s", a.type, b.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.NOT:
                    auto a = pop();
                    if (a.type == GsDynamicType.Number)
                        push(GsDynamic(!a.asNumber));
                    else
                    {
                        writefln("Fatality: logical NOT of %s", a.type);
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.CAT:
                    auto b = pop();
                    auto a = pop();
                    if (a.type == GsDynamicType.Array)
                    {
                        auto arr = a.asArray;
                        push(GsDynamic(arr ~ b));
                    }
                    else
                    {
                        push(GsDynamic(a.toString() ~ b.toString()));
                    }
                    break;
                case GsInstructionType.EQ:
                    auto b = pop();
                    auto a = pop();
                    push(GsDynamic(a == b));
                    break;
                case GsInstructionType.LESS:
                    auto b = pop().asNumber;
                    auto a = pop().asNumber;
                    push(GsDynamic(a < b));
                    break;
                case GsInstructionType.GREATER:
                    auto b = pop().asNumber;
                    auto a = pop().asNumber;
                    push(GsDynamic(a > b));
                    break;
                case GsInstructionType.NEQ:
                    auto b = pop();
                    auto a = pop();
                    push(GsDynamic(a != b));
                    break;
                case GsInstructionType.LESS_EQ:
                    auto b = pop().asNumber;
                    auto a = pop().asNumber;
                    push(GsDynamic(a <= b));
                    break;
                case GsInstructionType.GREATER_EQ:
                    auto b = pop().asNumber;
                    auto a = pop().asNumber;
                    push(GsDynamic(a >= b));
                    break;
                case GsInstructionType.JMP:
                    ip = jumpTable[instruction.operand.asString];
                    break;
                case GsInstructionType.JMP_IF:
                    if (cast(bool)pop().asNumber)
                        ip = jumpTable[instruction.operand.asString];
                    break;
                case GsInstructionType.JMP_IF_NOT:
                    if (!cast(bool)pop().asNumber)
                        ip = jumpTable[instruction.operand.asString];
                    break;
                case GsInstructionType.INDEX_GET:
                    size_t index = cast(size_t)pop().asNumber;
                    auto arrayParam = pop();
                    if (arrayParam.type == GsDynamicType.Array)
                    {
                        auto array = arrayParam.asArray;
                        if (index >= 0 && index < array.length)
                        {
                            push(array[index]);
                            break;
                        }
                        else
                        {
                            writeln("Fatality: index is outside array capability");
                            finalize();
                            return;
                        }
                    }
                    else if (arrayParam.type == GsDynamicType.String)
                    {
                        auto str = arrayParam.asString;
                        if (index >= 0 && index < str.length)
                        {
                            push(GsDynamic(cast(double)str[index]));
                            break;
                        }
                        else
                        {
                            writeln("Fatality: index is outside string length");
                            finalize();
                            return;
                        }
                    }
                    else
                    {
                        writefln("Fatality: attempting to index %s which is not an array", arrayParam.type);
                        finalize();
                        return;
                    }
                case GsInstructionType.INDEX_SET:
                    size_t index = cast(size_t)pop().asNumber;
                    auto arrayParam = pop();
                    if (arrayParam.type == GsDynamicType.Array)
                    {
                        auto array = arrayParam.asArray;
                        auto value = pop();
                        if (index >= 0 && index < array.length)
                            array[index] = value;
                        else
                        {
                            writeln("Fatality: index is outside array capability");
                            finalize();
                            return;
                        }
                        push(value);
                        break;
                    }
                    else
                    {
                        writefln("Fatality: attempting to index %s which is not an array", arrayParam.type);
                        finalize();
                        return;
                    }
                case GsInstructionType.LENGTH:
                    auto array = pop();
                    push(GsDynamic(array.asArray.length));
                    break;
                case GsInstructionType.PRINT:
                    writeln(pop());
                    break;
                case GsInstructionType.GLOBAL:
                    push(GsDynamic(this));
                    break;
                case GsInstructionType.ARRAY:
                    size_t len = cast(size_t)pop().asNumber;
                    auto arr = createArray(len);
                    for (size_t i = 0; i < len; i++)
                    {
                        arr[$ - 1 - i] = pop();
                    }
                    push(GsDynamic(arr));
                    break;
                case GsInstructionType.CALL:
                    size_t numParams = cast(size_t)instruction.operand.asNumber;
                    
                    auto func = pop();
                    
                    GsNativeMethod nativeMethod;
                    GsNativeFunc nativeFuncPtr;
                    bool useNativeMethod = false;
                    bool useNativeFunc = false;
                    
                    if (func.type == GsDynamicType.NativeMethod)
                    {
                        nativeMethod = func.asNativeMethod;
                        useNativeMethod = true;
                    }
                    else if (func.type == GsDynamicType.NativeFunction)
                    {
                        nativeFuncPtr = func.asNativeFunction;
                        useNativeFunc = true;
                    }
                    else
                    {
                        if (func.type == GsDynamicType.String)
                        {
                            string funcName = func.asString;
                            if (funcName in jumpTable)
                            {
                                callStack[cp] = ip; // Push the current instruction pointer onto the call stack
                                // Push a new call frame
                                cp++;
                                callFrame = &callFrames[cp];
                                for(size_t i = 0; i < callFrame.parameters.length; i++)
                                {
                                    if (i < numParams)
                                        callFrame.parameters[numParams - 1 - i] = pop();
                                    else
                                        callFrame.parameters[i] = GsDynamic();
                                }
                                callFrame.numParameters = numParams;
                                
                                ip = jumpTable[funcName]; // Jump to the function's starting instruction
                                
                                callDepth++;
                                
                                break;
                            }
                            else if (funcName in builtins)
                            {
                                auto nativeFunc = builtins[funcName];
                                
                                if (nativeFunc.type == GsDynamicType.NativeMethod)
                                {
                                    nativeMethod = nativeFunc.asNativeMethod;
                                    useNativeMethod = true;
                                }
                                else if (nativeFunc.type == GsDynamicType.NativeFunction)
                                {
                                    nativeFuncPtr = nativeFunc.asNativeFunction;
                                    useNativeFunc = true;
                                }
                                else
                                {
                                    writeln("Fatality: unsupported native call for function \"%s\"", funcName);
                                    finalize();
                                    return;
                                }
                            }
                            else
                            {
                                writefln("Fatality: undefined jump label \"%s\"", funcName);
                                finalize();
                                return;
                            }
                        }
                        else
                        {
                            writefln("Fatality: attempting to call %s, which is not a function", func.type);
                            finalize();
                            return;
                        }
                    }
                    
                    // Native call: push a new call frame
                    cp++;
                    callFrame = &callFrames[cp];
                    for(size_t i = 0; i < callFrame.parameters.length; i++)
                    {
                        if (i < numParams)
                            callFrame.parameters[numParams - 1 - i] = pop();
                        else
                            callFrame.parameters[i] = GsDynamic();
                    }
                    callFrame.numParameters = numParams;
                    
                    GsDynamic result;
                    if (useNativeMethod)
                        result = nativeMethod(callFrame.parameters[0..numParams]);
                    else if (useNativeFunc)
                        result = nativeFuncPtr(callFrame.parameters[0..numParams]);
                    
                    cp--;
                    callFrame = &callFrames[cp];
                    push(result);
                    
                    break;
                case GsInstructionType.RET:
                    if (callDepth > 0)
                    {
                        cp--;
                        ip = callStack[cp]; // Pop the return address from the call stack
                        callFrame = &callFrames[cp];
                        callDepth--;
                    }
                    else
                    {
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.STORE_VAR:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    callFrames[cp].localVariables[vIndex] = peek(); // Store a value into a local variable
                    break;
                case GsInstructionType.LOAD_VAR:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    push(callFrames[cp].localVariables[vIndex]); // Load a local variable onto the stack
                    break;
                case GsInstructionType.STORE_ARG:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    callFrames[cp].parameters[vIndex] = peek(); // Store a stack value into a parameter
                    break;
                case GsInstructionType.LOAD_ARG:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    push(callFrames[cp].parameters[vIndex]); // Load a parameter onto the stack
                    break;
                case GsInstructionType.LOAD_ARGS:
                    auto frame = &callFrames[cp];
                    push(GsDynamic(frame.parameters[0..frame.numParameters])); // Load all parameters onto the stack
                    break;
                case GsInstructionType.GLOBAL_STORE_VAR:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    callFrames[0].localVariables[vIndex] = peek(); // Store a value into a global variable
                    break;
                case GsInstructionType.GLOBAL_LOAD_VAR:
                    size_t vIndex = cast(size_t)instruction.operand.asNumber;
                    push(callFrames[0].localVariables[vIndex]); // Load a global variable onto the stack
                    break;
                case GsInstructionType.NEW:
                    auto obj = createObject();
                    push(GsDynamic(obj));
                    break;
                case GsInstructionType.REUSE:
                    auto param = pop();
                    if (param.type == GsDynamicType.Object)
                    {
                        auto newObj = createObject();
                        //newObj.set("__proto__", param);
                        newObj.setPrototype(param.asObject);
                        push(GsDynamic(newObj));
                    }
                    else
                    {
                        writeln("Fatality: attempting to reuse non-object");
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.GET:
                    auto key = instruction.operand.asString;
                    auto param = pop();
                    if (param.type == GsDynamicType.Object)
                    {
                        push(param.asObject.get(key));
                    }
                    else
                    {
                        writeln("Fatality: attempting to read member \"", key, "\" of non-object");
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.SET:
                    auto key = instruction.operand.asString;
                    auto param = pop();
                    auto value = pop();
                    if (param.type == GsDynamicType.Object)
                    {
                        param.asObject.set(key, value);
                        push(value);
                        break;
                    }
                    else
                    {
                        writeln("Fatality: attempting to write member \"", key, "\" of non-object");
                        finalize();
                        return;
                    }
                case GsInstructionType.INIT_SET:
                    auto key = instruction.operand.asString;
                    auto value = pop();
                    auto param = peek();
                    if (param.type == GsDynamicType.Object)
                    {
                        param.asObject.set(key, value);
                        break;
                    }
                    else
                    {
                        writeln("Fatality: attempting to write member \"", key, "\" of non-object");
                        finalize();
                        return;
                    }
                case GsInstructionType.CONTAINS:
                    auto key = instruction.operand.asString;
                    auto param = pop();
                    if (param.type == GsDynamicType.Object)
                    {
                        push(GsDynamic(param.asObject.contains(key)));
                    }
                    else
                    {
                        writeln("Fatality: attempting to read member \"", key, "\" of non-object");
                        finalize();
                        return;
                    }
                    break;
                case GsInstructionType.HALT:
                    finalize();
                    return;
                default:
                    writeln("Fatality: unknown instruction: ", instruction.type);
                    finalize();
                    return;
            }
        }
        
        finalize();
    }
}
