/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import std.stdio;
import std.conv;
import std.variant;
import std.file;
import std.path;
import gscript.instruction_set;
import gscript.vm;
import gscript.assembler;
import gscript.serializer;
import gscript.compiler;

class TestObj: GsObject
{
    int x = 0;
    
    this()
    {
    }
    
    void foo(GsVirtualMachine vm, size_t argc)
    {
        assert(argc == 0);
        writeln("TestObj.foo called");
    }
    
    Variant get(string key)
    {
        if (key == "x")
            return Variant(cast(double)x);
        else if (key == "foo")
            return Variant(&foo);
        else
            return Variant(cast(double)0.0);
    }
    
    void set(string key, Variant value)
    {
        if (key == "x")
            x = cast(int)value.get!double;
    }
    
    bool contains(string key)
    {
        if (key == "x") return true;
        else if (key == "foo") return true;
        else return false;
    }
    
    GsObject dup()
    {
        TestObj newObj = new TestObj();
        newObj.x = x;
        return newObj;
    }
}

Variant printSum(Variant[] args)
{
    auto b = args[0]; // Get the second argument
    auto a = args[1]; // Get the first argument
    writeln("printSum: ", a + b);
    return Variant(0);
}

void main(string[] args)
{
    GsInstruction[] instructions;
    bool saveCode = false;
    
    if (args.length < 2)
        return;
    
    string inputFilename = args[1];
    string inputExtension = extension(inputFilename);
    
    if (args.length >= 2)
    {
        if (inputExtension == ".gsa")
        {
            string program = readText(inputFilename);
            instructions = assemble(program);
            saveCode = true;
        }
        else if (inputExtension == ".gsc")
        {
            ubyte[] code = cast(ubyte[])std.file.read(inputFilename);
            instructions = loadBytecode(code);
        }
        else
        {
            string script = readText(inputFilename);
            instructions = compile(script, inputFilename);
            saveCode = true;
        }
    }
    else
        return;

    if (instructions.length == 0)
        return;

    writeln(instructions);
    
    TestObj test = new TestObj();
    Variant[] arr = [Variant(0.0), Variant(40.0), Variant("Hello, World!"), Variant(&printSum)];

    auto vm = new GsVirtualMachine();
    vm.set("foo", Variant(100));
    vm.set("printSum", Variant(&printSum));
    vm.set("test", Variant(test));
    vm.set("arr", Variant(arr));
    vm.load(instructions);
    vm.run();
    
    if (saveCode)
    {
        ubyte[] code = saveBytecode(instructions);
        string outputFilename = baseName(inputFilename, inputExtension) ~ ".gsc";
        std.file.write(outputFilename, code);
    }
}
